spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL
      username: sa
      password:
      driver-class-name: org.h2.Driver